steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y postgresql-client
        git clone https://github.com/[USERNAME]/[REPO_NAME].git /tmp/repo
        psql -h poised-sunrise-390308:us-central1:test1 -U postgres -d dbtest -f /tmp/repo/ddltest
 

options:
  timeout: 180s

options:
  logging: CLOUD_LOGGING_ONLY

  
