steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        git clone https://github.com/VivekGopalakrishnan/test1.git /tmp/repo
        psql -h poised-sunrise-390308:us-central1:test1 -U postgres -d postgres -f /tmp/repo/[DDL_SCRIPT_FILE]

options:
  timeout: 180s
